import type { Puzzle } from '../types/chess';

export const ACADEMY_PUZZLES: Puzzle[] = [
  {
    id: 'pz-01',
    title: 'The Royal Knight Fork',
    theme: 'Knight Fork',
    difficulty: 'Beginner',
    description: 'White has an explosive knight leap that attacks both Black\'s King and Queen simultaneously.',
    fen: 'r1bqk2r/pppp1ppp/2n5/4p3/2B1n3/2P2N2/PPP2PPP/R1BQK2R w KQkq - 0 6',
    playerColor: 'w',
    solutionMoves: ['c4f7', 'e8f7', 'd1d5'],
    hints: [
      'Look for a sacrifice on f7 that drags the Black King into the open.',
      'After the King captures on f7, your Queen can deliver a double attack on d5.',
    ],
    explanation: 'Bxf7+! forces Kxf7, allowing Qd5+! to fork the King on f7 and the active Knight on e4, regaining material with a decisive lead in development.',
  },
  {
    id: 'pz-02',
    title: 'Classic Back-Rank Checkmate',
    theme: 'Back-Rank Mate',
    difficulty: 'Beginner',
    description: 'Black\'s king is trapped behind an undisturbed pawn shield on the 8th rank. Find the punishing combination.',
    fen: '3r2k1/5ppp/8/8/8/8/3R1PPP/6K1 w - - 0 1',
    playerColor: 'w',
    solutionMoves: ['d2d8'],
    hints: [
      'Black has no luft (escape square) on the back rank.',
      'Capture the rook on d8 with checkmate.',
    ],
    explanation: 'Rxd8# delivers back-rank checkmate because Black\'s f7, g7, and h7 pawns trap their own king with no available retreat square.',
  },
  {
    id: 'pz-03',
    title: 'The Legendary Greek Gift Sacrifice',
    theme: 'Greek Gift',
    difficulty: 'Intermediate',
    description: 'White can sacrifice the bishop on h7 to shatter Black\'s kingside fortress and launch a lethal attack.',
    fen: 'r1bq1rk1/ppp2ppp/2n1pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQ - 0 7',
    playerColor: 'w',
    solutionMoves: ['d3h7', 'g8h7', 'f3g5'],
    hints: [
      'Consider the thematic sacrifice on the h7 square.',
      'After the King takes, Ng5+ follows with Qh5 on the horizon.',
    ],
    explanation: 'Bxh7+! Kxh7 Ng5+! forces the King away and opens the path for Qh5, with irresistible mating threats along the h-file.',
  },
  {
    id: 'pz-04',
    title: 'Smothered Checkmate',
    theme: 'Smothered Mate',
    difficulty: 'Master',
    description: 'A breathtaking queen sacrifice that leaves the enemy king suffocated by its own defending pieces.',
    fen: '6k1/5ppp/8/8/8/8/1Q4PP/5NNK w - - 0 1',
    playerColor: 'w',
    solutionMoves: ['b2b8'],
    hints: [
      'Infiltrate the 8th rank with your Queen.',
    ],
    explanation: 'Qb8# delivers immediate checkmate on the back rank.',
  },
  {
    id: 'pz-05',
    title: 'Absolute Pin Extraction',
    theme: 'Pin & Win',
    difficulty: 'Beginner',
    description: 'Black\'s Knight on c6 is pinned to their King on e8. Attack the pinned piece to win material.',
    fen: 'r1bqk2r/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4',
    playerColor: 'w',
    solutionMoves: ['b5c6', 'd7c6', 'f3e5'],
    hints: [
      'Remove the pinned knight defending e5.',
      'Capture the undefended central pawn on e5 next.',
    ],
    explanation: 'Bxc6+ bxc6 Nxe5 wins the e5 pawn cleanly because the knight was pinned and unable to protect the center.',
  },
  {
    id: 'pz-06',
    title: 'The Discovered Double Attack',
    theme: 'Discovered Attack',
    difficulty: 'Intermediate',
    description: 'Moving your bishop reveals a deadly rook battery while creating a second simultaneous threat.',
    fen: 'r1bqkb1r/pp2pppp/2n5/1B1p4/3P4/8/PPP2PPP/R1BQK1NR w KQkq - 0 7',
    playerColor: 'w',
    solutionMoves: ['c2c4', 'd5c4', 'd1a4'],
    hints: [
      'Create a double attack on the pinned c6 knight with your Queen.',
    ],
    explanation: 'Qa4! targets the pinned knight on c6 with Queen and Bishop, forcing Black into defensive capitulation.',
  },
  {
    id: 'pz-07',
    title: 'Deflection of the Royal Guard',
    theme: 'Deflection',
    difficulty: 'Intermediate',
    description: 'White can deflect Black\'s queen away from guarding the crucial d8 square.',
    fen: '3r2k1/p4ppp/1p6/8/8/1Q2B3/PP3PPP/3R2K1 w - - 0 1',
    playerColor: 'w',
    solutionMoves: ['d1d8'],
    hints: [
      'Trade rooks with checkmate on d8.',
    ],
    explanation: 'Rxd8# exploits the absence of back-rank defenders, converting directly into a mating attack.',
  },
  {
    id: 'pz-08',
    title: 'Endgame Passed Pawn Breakthrough',
    theme: 'Pawn Breakthrough',
    difficulty: 'Master',
    description: 'Three connected pawns against three. Find the sacrificial breakthrough to promote a queen first.',
    fen: '8/8/8/4k3/1PPP4/8/8/4K3 w - - 0 1',
    playerColor: 'w',
    solutionMoves: ['d4d5'],
    hints: [
      'Push the central passed pawn to disrupt the enemy king.',
    ],
    explanation: 'd5+! creates a protected passed pawn barrier that rolls unstoppable into a new Queen.',
  },
];
